export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_ERRORS = 'SIGN_UP_ERRORS';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const GET_MEALS = 'GET_MEALS ';
