export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_ERRORS = 'SIGN_UP_ERRORS';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const GET_MEALS = 'GET_MEALS ';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_FAIL = 'GET_ORDER_HISTORY_FAIL';
export const GET_SINGLE_MENU = 'GET_SINGLE_MENU';
export const GET_SINGLE_MENU_FAIL = 'GET_SINGLE_MENU_FAIL';
export const FETCH_ORDER_HISTORY = 'FETCH_ORDER_HISTORY';
export const FETCH_ORDER_HISTORY_FAIL = 'FETCH_ORDER_HISTORY_FAIL';

